### ISSUE TITLE
Estimated Amplitudes too Small

### ISSUE THREAD

**Issue by gdepalma** [maytesuarezfarinas/cosinoRmixedeffects#2]
Hello -

I really appreciate the effort in putting this package together.  I find it very useful.

I've noticed my estimated amplitudes from the `get.means.cs.cosinor` seem small, especially when compared to the coefficients.  I've attached two screenshots where I calculate the amplitudes by the model estimates and from the `get.means.cs.cosinor`.

Digging deeper, in the `just.get.means.cosinor` function only the `rrr` term is used in the calculation of amplitude.  I believe it is missing the `sss` term.

Thanks
Glen

![estimated_amp_model](https://user-images.githubusercontent.com/3226969/160467901-1f667575-e93e-4543-becb-082697534023.png)
![db_means](https://user-images.githubusercontent.com/3226969/160467989-9c2c07fb-c5ab-4540-b9a5-792bcdd77c31.png)

**Comment by maytesuarezfarinas** [comment]
This error has been fixed
